/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 1.7.0 from webgme on Tue Jul 18 2017 11:48:07 GMT-0500 (CDT).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */

define([
    'plugin/PluginConfig',
    'text!./metadata.json',
    'plugin/PluginBase'
], function (
    PluginConfig,
    pluginMetadata,
    PluginBase) {
    'use strict';

    pluginMetadata = JSON.parse(pluginMetadata);

    /**
     * Initializes a new instance of testrouter.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin testrouter.
     * @constructor
     */
    var testrouter = function () {
        // Call base class' constructor.
        PluginBase.call(this);
        this.pluginMetadata = pluginMetadata;
    };

    /**
     * Metadata associated with the plugin. Contains id, name, version, description, icon, configStructue etc.
     * This is also available at the instance at this.pluginMetadata.
     * @type {object}
     */
    testrouter.metadata = pluginMetadata;

    // Prototypical inheritance from PluginBase.
    testrouter.prototype = Object.create(PluginBase.prototype);
    testrouter.prototype.constructor = testrouter;

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    testrouter.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        var self = this,
            nodeObject;


        // Using the logger.
        self.logger.debug('This is a debug message.');
        self.logger.info('This is an info message.');
        self.logger.warn('This is a warning message.');
        self.logger.error('This is an error message.');

        // Using the coreAPI to make changes.

        nodeObject = self.activeNode;
        self.core.setAttribute(nodeObject, 'name', 'My new obj1');
        self.core.setRegistry(nodeObject, 'position', {x: 70, y: 70});

        self.core.setAttribute(nodeObject,'router',100)


        self.sendNotification("router_test2::My new obj1::info::meta updated")


        // This will save the changes. If you don't want to save;
        // exclude self.save and call callback directly from this scope.

        self.save('testrouter updated model.')
            .then(function () {
                self.result.setSuccess(true);
                // callback(null, self.result);
                callback(null, self.result);
            })
            .catch(function (err) {
                // Result success is false at invocation.
                callback(err, self.result);
            });

    };

    return testrouter;
});
