// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');
config.rest.components['routers/pingmachine'] = __dirname + '/../src/routers/pingmachine/pingmachine.js';

// Visualizer descriptors

// Add requirejs paths
// Allow server execution
config.plugin.allowServerExecution = true

config.webhooks.enable = true

config.mongo.uri = 'mongodb://127.0.0.1:27017/sanjaya';
validateConfig(config);
module.exports = config;
